app/models.py
from flask import Flask,url_for
from flask_sqlalchemy import SQLAlchemy
db=SQLAlchemy()
class Book(db.Model):
    __tablename__="book"
    id=db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String(20))
    cover_photo=db.Column(db.String(50))
    number_of_pages=db.Column(db.Integer)
    description=db.Column(db.String(100))

    @property
    def image_url(self):
        return url_for ("static",filename=f"images/{self.cover_photo}")

    @property
    def show_url(self):
        return url_for ("book.show",id=self.id)
    @property
    def delete_url(self):
        return url_for ("book.delete",id=self.id)

app/book/forms.py
from flask import Flask
from flask_wtf import FlaskForm
from wtforms import StringField,IntegerField, SubmitField,FileField
from wtforms.validators import DataRequired, Length,Regexp


class PostForm(FlaskForm):
    title= StringField("Title", validators=[DataRequired(), Length(3,20)
    ,Regexp(r'^[A-Za-z\s]+$', message="please type characters only")])
    description = StringField("Description",validators=[DataRequired(),Length(20,100)])
    number_of_pages=IntegerField("number_of_pages",validators=[DataRequired()])
    image= FileField("Image", validators=[DataRequired()])
    submit = SubmitField("Create Book")

class EditForm(FlaskForm):
    title = StringField("Name", validators=[ Length(3, 20)
    ,Regexp(r'^[A-Za-z\s]+$', message="please type characters only")])
    description = StringField("Description",validators=[Length(20,100)])
    number_of_pages=IntegerField("number_of_pages")
    image= FileField("Image")
    submit = SubmitField("Edit Book")

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from app.config import productionConfig
from app.models import db
from app.book import landing_blueprint,book_blueprint
from flask_bootstrap import Bootstrap5


def create_app():
    app=Flask(__name__)
    app.config.from_object(productionConfig)
    db.init_app(app)
    migrate=Migrate(app,db)
    app.register_blueprint(landing_blueprint)
    app.register_blueprint(book_blueprint)
    bootstrap=Bootstrap5(app)

    return app


    
    

app/book/__init__.py
from flask import Blueprint
book_blueprint=Blueprint("book",__name__,url_prefix="/book")
landing_blueprint=Blueprint("landing",__name__,url_prefix="/")
from app.book import views

app/book/views.py
from flask import Flask
from app.book import book_blueprint,landing_blueprint
from app.models import Book,db
from flask import render_template,request,redirect,url_for
from app.book.forms import PostForm,EditForm
from werkzeug.utils import secure_filename
import os


@landing_blueprint.route("",endpoint="landing")
def landing():
    books=Book.query.all()
    return render_template("landing.html",books=books)

@book_blueprint.route("<int:id>/show",endpoint="show")
def show(id):
    book = db.get_or_404(Book, id)
    return render_template ("show.html",book=book)

@book_blueprint.route("<int:id>/delete",endpoint="delete")
def delete(id):
    book = db.get_or_404(Book, id)
    db.session.delete(book)
    db.session.commit()
    return redirect (url_for("landing.landing"))

@book_blueprint.route("/form/add",endpoint="add",methods=['GET','POST'])
def add():
    form=PostForm()
    if request.method=="POST":
        if form.validate_on_submit():
                request.files.get("cover_photo")
                image=form.image.data
                image_name =secure_filename(image.filename)
                image.save(os.path.join('static/images/', image_name))
                data=dict(request.form)
                del data['csrf_token']
                del data['submit']
                data["cover_photo"]=image_name
                book=Book(**data)
                db.session.add(book)
                db.session.commit()
                return redirect(url_for("landing.landing"))
            
        
    return render_template("add.html",form=form)


@book_blueprint.route("<int:id>/form/edit",endpoint="edit",methods=['GET','POST'])
def edit(id):
    book=db.get_or_404(Book,id)
    form=EditForm(obj=book)
    if request.method=="POST":
        if form.validate_on_submit():
                if request.files.get("cover_photo"):
                    image=form.image.data
                    image_name =secure_filename(image.filename)
                    image.save(os.path.join('static/images/', image_name))
                    book.cover_photo=image_name
                else:
                    book.cover_photo=book.cover_photo
                book.title=form.title.data
                book.number_of_pages=form.number_of_pages.data
                book.description=form.description.data
                db.session.commit()
                return redirect(url_for("landing.landing"))
            
        
    return render_template("edit.html",form=form)

app/templates/add.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/add.css') }}">

{%endblock%}

{% block main %}

<div class="  d-flex flex-column justify-content-center">
    <h1>Please Enter Book Details </h1>
    <div class="parentDiv">{{ render_form(form) }}</div>
</div>

{%endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %} 

    {% endblock %}
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>

<body>

    {% block main %}
   
    {% endblock %}
</body>
</html>

app/templates/edit.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/edit.css') }}">

{%endblock%}

{% block main %}

<div class="  d-flex flex-column justify-content-center">
    <h1>Update Your Book Details </h1>
    <div class="parentDiv">{{ render_form(form) }}</div>
</div>

{%endblock%}

app/templates/landing.html
{% extends "base.html" %}
{% block title %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/landing.css') }}">

{% endblock %}

{% block main %}
<div class="d-flex flex flex-column  align-items-center w-100">
    <h1>Welcome To Omar's BookStore</h1>
    <a href="{{url_for('book.add')}} " class="btn btn-dark buttonAdd w-25 mt-3">Add Book</a>
</div>
<div class="d-flex">
{% for book in books%}
<div class="card mx-2 my-3" style="width: 20rem;">
    <img class="card-img-top" src="{{ book.image_url }}" alt="{{ book.title }}" style=" height: 30rem;">
         
   <div class="card-body">
    <div class="text-center">
     <h5 class="card-title">{{book.title}}</h5>
     <p class="card-text">{{book.description}}</p>
     <label >Pages:</label><p class="d-inline pages mb-5">{{book.number_of_pages}}</p>
     <br>
     
     <a href="{{book.show_url}}" class="btn btn-dark mb-3 mt-2">Show Details</a>
    </div>
   </div>
 </div>
 {% endfor %}
</div>
{% endblock %}

app/templates/show.html
{% extends "base.html" %}
{% block title %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/show.css') }}">

{% endblock %}

{% block main %}
<div class="card " style="width: 30rem; height:30rem; margin:auto;">
    <img class="card-img-top" src="{{ book.image_url }}" alt="{{ book.title }}" style=" height: 30rem;">
         
   <div class="card-body">
     <h5 class="card-title">{{book.title}}</h5>
     <p class="card-text">{{book.description}}</p>
     <div class="d-flex justify-content-between">
     <a href="{{book.delete_url}}" class="btn btn-dark ms-5 w-25">Delete</a>
     <a href="{{url_for('book.edit',id=book.id)}}" class="btn btn-dark me-5 w-25">Edit</a>
    </div>
   </div>
 </div>

{% endblock %}